-- PhishGraph Snowflake setup
-- Run this in Snowsight using a role that can create a database/schema/tables.
-- If your organization does not allow CREATE DATABASE, ask an administrator
-- to create PHISHGRAPH_DB and then run the table statements inside that database.

CREATE DATABASE IF NOT EXISTS PHISHGRAPH_DB;
USE DATABASE PHISHGRAPH_DB;

CREATE SCHEMA IF NOT EXISTS PUBLIC;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS MESSAGES (
    MESSAGE_ID VARCHAR,
    SENDER_DOMAIN VARCHAR,
    SUBJECT VARCHAR,
    MESSAGE_TEXT VARCHAR,
    NUM_LINKS INTEGER,
    SUSPICIOUS_KEYWORDS INTEGER,
    DOMAIN_RISK FLOAT,
    SENDER_KNOWN BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MESSAGE_FEATURES (
    MESSAGE_ID VARCHAR,
    KEYWORD_SCORE FLOAT,
    UNKNOWN_SENDER_SCORE FLOAT,
    LINK_SCORE FLOAT,
    URGENCY_SCORE FLOAT,
    DOMAIN_SCORE FLOAT,
    CORTEX_RAW VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RISK_RESULTS (
    MESSAGE_ID VARCHAR,
    KEYWORD_POINTS FLOAT,
    UNKNOWN_SENDER_POINTS FLOAT,
    LINK_POINTS FLOAT,
    URGENCY_POINTS FLOAT,
    DOMAIN_POINTS FLOAT,
    RISK_SCORE FLOAT,
    RISK_LEVEL VARCHAR,
    EXPLANATION VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Optional checks:
SHOW TABLES;
SELECT CURRENT_ACCOUNT(), CURRENT_USER(), CURRENT_ROLE(), CURRENT_WAREHOUSE();
